### ISSUE TITLE
Navigation Bar: navigation bar disappears when you make your screen smaller 

### ISSUE THREAD

**Issue by kathyduarte** [ucsc/ucsc-gutenberg-blocks#24] opened 2022-04-29 19:12 UTC
same issue occurs when you open the website on your  mobile phones

https://user-images.githubusercontent.com/62771705/166019867-d8ff702b-22c5-42e4-b298-5f364024a14f.mov

**Comment by superkumario64** [comment] 2022-04-29 20:33
@kathyduarte this repo is for Campus Directory, Class Schedule and Course Catalog. I'm going to close this issue.

**Closed by superkumario64** 2022-04-29 20:33 UTC

**Comment by Herm71** [comment] 2022-05-17 21:21
That's a feature. Not a bug. It's supposed to do that.
